/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Team = {
  _id: string
  _type: 'team'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  role: string
  github?: string
  x?: string
  bio: BasicTextEditor
  picture: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type BasicTextEditor = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'blockquote'
  listItem?: 'bullet'
  markDefs?: Array<{
    href?: string
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type NotFound = {
  _id: string
  _type: 'not-found'
  _createdAt: string
  _updatedAt: string
  _rev: string
  eyebrow?: string
  title: string
  content?: BasicTextEditor
  items?: Array<{
    type?: 'internal' | 'external'
    external?: External
    internal?: Internal
    _type: 'link'
    _key: string
  }>
}

export type Homepage = {
  _id: string
  _type: 'homepage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  excerpt?: string
  link: Internal
  image: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  slices?: Array<
    | ({
        _key: string
      } & CallToAction)
    | ({
        _key: string
      } & CenteredText)
    | ({
        _key: string
      } & ImageCarousel)
    | ({
        _key: string
      } & Subscribe)
    | ({
        _key: string
      } & TeamMembers)
    | ({
        _key: string
      } & TextBlockWithImage)
  >
}

export type Internal = {
  _type: 'internal'
  reference?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'page'
  }
  label?: string
}

export type Menu = {
  _id: string
  _type: 'menu'
  _createdAt: string
  _updatedAt: string
  _rev: string
  items?: Array<{
    type?: 'internal' | 'external'
    external?: External
    internal?: Internal
    _type: 'link'
    _key: string
  }>
}

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  logo: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  links: {
    donation: string
    substack: string
    twitter: string
  }
  description: string
  ogImage: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  email: string
  gpg?: string
  disclaimer: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type FileList = {
  _type: 'file-list'
  background?: 'yellow' | 'white'
  eyebrow?: string
  title: string
  description?: string
  items?: Array<{
    name: string
    file: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
      }
      media?: unknown
      _type: 'file'
    }
    _type: 'item'
    _key: string
  }>
}

export type TextBlock = {
  _type: 'text-block'
  content?: TextEditor
}

export type Subscribe = {
  _type: 'subscribe'
  background?: 'yellow' | 'white'
  title: string
  description?: string
}

export type TextBlockWithImage = {
  _type: 'text-block-with-image'
  layout?: 'left' | 'right'
  content?: TextEditor
  image: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type TeamMembers = {
  _type: 'team-members'
  eyebrow?: string
  title?: string
  summary?: string
  variant?: 'teaser' | 'full'
  team: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'team'
  }>
  additional?: TextEditor
}

export type ImageCarousel = {
  _type: 'image-carousel'
  eyebrow?: string
  title: string
  text?: BasicTextEditor
  images: Array<{
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
    _key: string
  }>
}

export type Faqs = {
  _type: 'faqs'
  eyebrow?: string
  title: string
  content?: BasicTextEditor
  items: Array<{
    title: string
    content: TextEditor
    _key: string
  }>
}

export type Donors = {
  _type: 'donors'
  eyebrow?: string
  title: string
  content?: BasicTextEditor
  items: Array<{
    image: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
    name: string
    url: string
    _key: string
  }>
}

export type CenteredText = {
  _type: 'centered-text'
  layout?: 'above' | 'below'
  eyebrow?: string
  title: string
  content?: BasicTextEditor
  link?: Internal
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type CallToAction = {
  _type: 'call-to-action'
  layout?: 'left' | 'right'
  eyebrow?: string
  title: string
  content?: string
  link: Link
  image: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type TextEditor = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'eyebrow' | 'h2' | 'h3' | 'h4' | 'h5' | 'normal' | 'blockquote'
      listItem?: 'bullet'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
      _key: string
    }
  | ({
      _key: string
    } & Donate)
>

export type Donate = {
  _type: 'donate'
  settings?: string
}

export type Link = {
  _type: 'link'
  type?: 'internal' | 'external'
  external?: External
  internal?: Internal
}

export type External = {
  _type: 'external'
  url: string
  label: string
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  excerpt?: string
  slices?: Array<
    | ({
        _key: string
      } & CallToAction)
    | ({
        _key: string
      } & CenteredText)
    | ({
        _key: string
      } & Donors)
    | ({
        _key: string
      } & Faqs)
    | ({
        _key: string
      } & FileList)
    | ({
        _key: string
      } & ImageCarousel)
    | ({
        _key: string
      } & Subscribe)
    | ({
        _key: string
      } & TeamMembers)
    | ({
        _key: string
      } & TextBlock)
    | ({
        _key: string
      } & TextBlockWithImage)
  >
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | Team
  | SanityImageCrop
  | SanityImageHotspot
  | BasicTextEditor
  | NotFound
  | Homepage
  | Internal
  | Menu
  | Settings
  | FileList
  | TextBlock
  | Subscribe
  | TextBlockWithImage
  | TeamMembers
  | ImageCarousel
  | Faqs
  | Donors
  | CenteredText
  | CallToAction
  | TextEditor
  | Donate
  | Link
  | External
  | Page
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
export declare const internalGroqTypeReferenceTo: unique symbol
// Source: ./sanity/lib/queries.ts
// Variable: allPagesQuery
// Query: *[_type == "page"] { "slug": slug.current }
export type AllPagesQueryResult = Array<{
  slug: string
}>
// Variable: settingsQuery
// Query: *[_type == "settings"][0] {  ...,  disclaimer[] {    ...  }}
export type SettingsQueryResult = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  logo: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  links: {
    donation: string
    substack: string
    twitter: string
  }
  description: string
  ogImage: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  email: string
  gpg?: string
  disclaimer: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
} | null
// Variable: menuQuery
// Query: *[_type == "menu"][0] {  items[] {    ...,    internal {      "_type": _type,      "label": label,      "slug": reference->slug.current,      "document": reference->_type    },    external {      "_type": _type,      "label": label,      "url": url,    }  }}
export type MenuQueryResult = {
  items: Array<{
    type?: 'external' | 'internal'
    external: {
      _type: 'external'
      label: string
      url: string
    } | null
    internal: {
      _type: 'internal'
      label: string | null
      slug: string | null
      document: 'page' | null
    } | null
    _type: 'link'
    _key: string
  }> | null
} | null
// Variable: pageNotFoundQuery
// Query: *[_type == "not-found"][0] {    ...,    content[] {      ...,    },  }
export type PageNotFoundQueryResult = {
  _id: string
  _type: 'not-found'
  _createdAt: string
  _updatedAt: string
  _rev: string
  eyebrow?: string
  title: string
  content: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'blockquote' | 'normal'
    listItem?: 'bullet'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }> | null
  items?: Array<{
    type?: 'external' | 'internal'
    external?: External
    internal?: Internal
    _type: 'link'
    _key: string
  }>
} | null
// Variable: homepageQuery
// Query: *[_type == "homepage"][0] {    ...,    link {      "_type": _type,      "label": label,      "slug": reference->slug.current,      "document": reference->_type    },    slices[] {      ...,      content[] {        ...,      },      link {        internal {          "_type": _type,          "label": label,          "slug": reference->slug.current,          "document": reference->_type        },      },      _type == 'text-block-with-image' => {        ...,      },      _type == 'call-to-action' => {        ...,        link {          _key,          _id,          type,          internal {            "_type": _type,            "label": label,            "slug": reference->slug.current,            "document": reference->_type          },          external {            "_type": _type,            "label": label,            "url": url,          }        }      },      _type == 'centered-text' => {        ...,        link {          internal {            "_type": _type,            "label": label,            "slug": reference->slug.current,            "document": reference->_type          },        }      },      _type == 'team-members' => {      ...,      team[]->{        name,        role,        github,        content,        x,        bio,        picture      }    },    }  }
export type HomepageQueryResult = {
  _id: string
  _type: 'homepage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  excerpt?: string
  link: {
    _type: 'internal'
    label: string | null
    slug: string | null
    document: 'page' | null
  }
  image: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  slices: Array<
    | {
        _key: string
        _type: 'call-to-action'
        layout?: 'left' | 'right'
        eyebrow?: string
        title: string
        content?: string
        link: {
          _key: null
          _id: null
          type: 'external' | 'internal' | null
          internal: {
            _type: 'internal'
            label: string | null
            slug: string | null
            document: 'page' | null
          } | null
          external: {
            _type: 'external'
            label: string
            url: string
          } | null
        }
        image: {
          asset?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
          }
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          alt?: string
          _type: 'image'
        }
      }
    | {
        _key: string
        _type: 'centered-text'
        layout?: 'above' | 'below'
        eyebrow?: string
        title: string
        content?: BasicTextEditor
        link: {
          internal: null
        } | null
        image?: {
          asset?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
          }
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          alt?: string
          _type: 'image'
        }
      }
    | {
        _key: string
        _type: 'image-carousel'
        eyebrow?: string
        title: string
        text?: BasicTextEditor
        images: Array<{
          asset?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
          }
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          alt?: string
          _type: 'image'
          _key: string
        }>
        content: null
        link: null
      }
    | {
        _key: string
        _type: 'subscribe'
        background?: 'white' | 'yellow'
        title: string
        description?: string
        content: null
        link: null
      }
    | {
        _key: string
        _type: 'team-members'
        eyebrow?: string
        title?: string
        summary?: string
        variant?: 'full' | 'teaser'
        team: Array<{
          name: string
          role: string
          github: string | null
          content: null
          x: string | null
          bio: BasicTextEditor
          picture: {
            asset?: {
              _ref: string
              _type: 'reference'
              _weak?: boolean
              [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
            }
            media?: unknown
            hotspot?: SanityImageHotspot
            crop?: SanityImageCrop
            alt?: string
            _type: 'image'
          }
        }>
        additional?: TextEditor
        content: null
        link: null
      }
    | {
        _key: string
        _type: 'text-block-with-image'
        layout?: 'left' | 'right'
        content?: TextEditor
        image: {
          asset?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
          }
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          alt?: string
          _type: 'image'
        }
        link: null
      }
  > | null
} | null
// Variable: pageQuery
// Query: *[_type == "page" && slug.current == $slug][0] {    ...,    slices[] {      ...,      content[] {        ...,      },      link {        internal {          "_type": _type,          "label": label,          "slug": reference->slug.current,          "document": reference->_type        },      },      _type == 'text-block-with-image' => {        ...,      },      _type == 'call-to-action' => {        ...,        link {          _id,          type,          internal {            "_type": _type,            "label": label,            "slug": reference->slug.current,            "document": reference->_type          },          external {            "_type": _type,            "label": label,            "url": url,          }        }      },      _type == 'team-members' => {        ...,        team[]->{          name,          content,          role,          github,          x,          bio,          picture        }      },      _type == 'file-link' => {        ...,        items[]->{          name,          'file': file.asset->        }      },    }  }
export type PageQueryResult = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  excerpt?: string
  slices: Array<
    | {
        _key: string
        _type: 'call-to-action'
        layout?: 'left' | 'right'
        eyebrow?: string
        title: string
        content?: string
        link: {
          _id: null
          type: 'external' | 'internal' | null
          internal: {
            _type: 'internal'
            label: string | null
            slug: string | null
            document: 'page' | null
          } | null
          external: {
            _type: 'external'
            label: string
            url: string
          } | null
        }
        image: {
          asset?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
          }
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          alt?: string
          _type: 'image'
        }
      }
    | {
        _key: string
        _type: 'centered-text'
        layout?: 'above' | 'below'
        eyebrow?: string
        title: string
        content: Array<{
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?: 'blockquote' | 'normal'
          listItem?: 'bullet'
          markDefs?: Array<{
            href?: string
            _type: 'link'
            _key: string
          }>
          level?: number
          _type: 'block'
          _key: string
        }> | null
        link: {
          internal: null
        } | null
        image?: {
          asset?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
          }
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          alt?: string
          _type: 'image'
        }
      }
    | {
        _key: string
        _type: 'donors'
        eyebrow?: string
        title: string
        content: Array<{
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?: 'blockquote' | 'normal'
          listItem?: 'bullet'
          markDefs?: Array<{
            href?: string
            _type: 'link'
            _key: string
          }>
          level?: number
          _type: 'block'
          _key: string
        }> | null
        items: Array<{
          image: {
            asset?: {
              _ref: string
              _type: 'reference'
              _weak?: boolean
              [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
            }
            media?: unknown
            hotspot?: SanityImageHotspot
            crop?: SanityImageCrop
            alt?: string
            _type: 'image'
          }
          name: string
          url: string
          _key: string
        }>
        link: null
      }
    | {
        _key: string
        _type: 'faqs'
        eyebrow?: string
        title: string
        content: Array<{
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?: 'blockquote' | 'normal'
          listItem?: 'bullet'
          markDefs?: Array<{
            href?: string
            _type: 'link'
            _key: string
          }>
          level?: number
          _type: 'block'
          _key: string
        }> | null
        items: Array<{
          title: string
          content: TextEditor
          _key: string
        }>
        link: null
      }
    | {
        _key: string
        _type: 'file-list'
        background?: 'white' | 'yellow'
        eyebrow?: string
        title: string
        description?: string
        items?: Array<{
          name: string
          file: {
            asset?: {
              _ref: string
              _type: 'reference'
              _weak?: boolean
              [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
            }
            media?: unknown
            _type: 'file'
          }
          _type: 'item'
          _key: string
        }>
        content: null
        link: null
      }
    | {
        _key: string
        _type: 'image-carousel'
        eyebrow?: string
        title: string
        text?: BasicTextEditor
        images: Array<{
          asset?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
          }
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          alt?: string
          _type: 'image'
          _key: string
        }>
        content: null
        link: null
      }
    | {
        _key: string
        _type: 'subscribe'
        background?: 'white' | 'yellow'
        title: string
        description?: string
        content: null
        link: null
      }
    | {
        _key: string
        _type: 'team-members'
        eyebrow?: string
        title?: string
        summary?: string
        variant?: 'full' | 'teaser'
        team: Array<{
          name: string
          content: null
          role: string
          github: string | null
          x: string | null
          bio: BasicTextEditor
          picture: {
            asset?: {
              _ref: string
              _type: 'reference'
              _weak?: boolean
              [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
            }
            media?: unknown
            hotspot?: SanityImageHotspot
            crop?: SanityImageCrop
            alt?: string
            _type: 'image'
          }
        }>
        additional?: TextEditor
        content: null
        link: null
      }
    | {
        _key: string
        _type: 'text-block-with-image'
        layout?: 'left' | 'right'
        content?: TextEditor
        image: {
          asset?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
          }
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          alt?: string
          _type: 'image'
        }
        link: null
      }
    | {
        _key: string
        _type: 'text-block'
        content: Array<
          | {
              children?: Array<{
                marks?: Array<string>
                text?: string
                _type: 'span'
                _key: string
              }>
              style?:
                | 'blockquote'
                | 'eyebrow'
                | 'h2'
                | 'h3'
                | 'h4'
                | 'h5'
                | 'normal'
              listItem?: 'bullet'
              markDefs?: Array<{
                href?: string
                _type: 'link'
                _key: string
              }>
              level?: number
              _type: 'block'
              _key: string
            }
          | {
              _key: string
              _type: 'donate'
              settings?: string
            }
          | {
              asset?: {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
              }
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              alt?: string
              _type: 'image'
              _key: string
            }
        > | null
        link: null
      }
  > | null
} | null

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '\n    *[_type == "page"] { "slug": slug.current }\n  ': AllPagesQueryResult
    '*[_type == "settings"][0] {\n  ...,\n  disclaimer[] {\n    ...\n  }\n}': SettingsQueryResult
    '*[_type == "menu"][0] {\n  items[] {\n    ...,\n    internal {\n      "_type": _type,\n      "label": label,\n      "slug": reference->slug.current,\n      "document": reference->_type\n    },\n    external {\n      "_type": _type,\n      "label": label,\n      "url": url,\n    }\n  }\n}': MenuQueryResult
    '\n  *[_type == "not-found"][0] {\n    ...,\n    content[] {\n      ...,\n    },\n  }\n': PageNotFoundQueryResult
    '\n  *[_type == "homepage"][0] {\n    ...,\n    link {\n      "_type": _type,\n      "label": label,\n      "slug": reference->slug.current,\n      "document": reference->_type\n    },\n    slices[] {\n      ...,\n      content[] {\n        ...,\n      },\n      link {\n        internal {\n          "_type": _type,\n          "label": label,\n          "slug": reference->slug.current,\n          "document": reference->_type\n        },\n      },\n      _type == \'text-block-with-image\' => {\n        ...,\n      },\n      _type == \'call-to-action\' => {\n        ...,\n        link {\n          _key,\n          _id,\n          type,\n          internal {\n            "_type": _type,\n            "label": label,\n            "slug": reference->slug.current,\n            "document": reference->_type\n          },\n          external {\n            "_type": _type,\n            "label": label,\n            "url": url,\n          }\n        }\n      },\n      _type == \'centered-text\' => {\n        ...,\n        link {\n          internal {\n            "_type": _type,\n            "label": label,\n            "slug": reference->slug.current,\n            "document": reference->_type\n          },\n        }\n      },\n      _type == \'team-members\' => {\n      ...,\n      team[]->{\n        name,\n        role,\n        github,\n        content,\n        x,\n        bio,\n        picture\n      }\n    },\n    }\n  }\n': HomepageQueryResult
    '\n  *[_type == "page" && slug.current == $slug][0] {\n    ...,\n    slices[] {\n      ...,\n      content[] {\n        ...,\n      },\n      link {\n        internal {\n          "_type": _type,\n          "label": label,\n          "slug": reference->slug.current,\n          "document": reference->_type\n        },\n      },\n      _type == \'text-block-with-image\' => {\n        ...,\n      },\n      _type == \'call-to-action\' => {\n        ...,\n        link {\n          _id,\n          type,\n          internal {\n            "_type": _type,\n            "label": label,\n            "slug": reference->slug.current,\n            "document": reference->_type\n          },\n          external {\n            "_type": _type,\n            "label": label,\n            "url": url,\n          }\n        }\n      },\n      _type == \'team-members\' => {\n        ...,\n        team[]->{\n          name,\n          content,\n          role,\n          github,\n          x,\n          bio,\n          picture\n        }\n      },\n      _type == \'file-link\' => {\n        ...,\n        items[]->{\n          name,\n          \'file\': file.asset->\n        }\n      },\n    }\n  }\n': PageQueryResult
  }
}
